### ISSUE TITLE
[Feature Request] Support for assignment without space

### ISSUE THREAD

**Issue by hzhangxyz** [kongaskristjan/fire-hpp#8]
For example, we use `gcc -I/path/to/a/directory` without space between `-I` and `/path/to/a/directory`

**Comment by kongaskristjan** [comment]
I'd prefer not to support such constructs, because
1. To me, it seems outdated/bad CLI anyway
2. I have to be really careful of what to include in the library's interface. The mechanism the library works and discovers arguments is rather complex anyway, and adding new features now might render implementing more critical features later either very hard or impossible.

**Comment by kongaskristjan** [comment]
> To me, it seems outdated/bad CLI anyway

Sorry, my bad. I thought gcc forces the user to assign without space, but instead it just allows it in addition to regular space assignment. Thus I guess the proposal was to just silently accept assignment without space, instead of having a way to enforce assignment without space. Is my new understanding correct?

This would mostly invalidate my 2. argument as well, as the library's interface would remain exactly the same.

How common is supporting this kind of assignment? I know that at least some compilers support it (gcc, clang) and I've used make's -j flag.

Also, I guess this only works with single character named arguments (eg. `-I`, but not with `--longer`)? Otherwise you could have ambiguities, if for example your program accepts two arguments `--lo` and `--long`, but you type `./program --longer`.

**Comment by kongaskristjan** [comment]
I implemented the feature as described in my previous comment in f0e2a16bbc05c8066b50a1b5e3de4a10c2c733a8.

Thanks for opening the issue!
