### ISSUE TITLE
Add a dedicated LICENSE file

### ISSUE THREAD

**Issue by Croydon** [kongaskristjan/fire-hpp#9]
This makes packaging fire-hpp easier and makes it also easier to automatically detect and identify the license

**Comment by kongaskristjan** [comment]
A problem with having a licence file is that I currently use two different licences. For the library itself, I use MIT, as I still want a basic protection from copying the project and claiming it's the copier's work. Examples, however, are meant to be blatantly copied into whatever project without any notice, and thus I use 0BSD. One option is to have everything under MIT and simply hope that people don't feel guilty about copying examples.

Btw, do you have a specific package manager in mind?

**Comment by Croydon** [comment]
You could add a MIT `LICENSE` file to the root and a second 0BSD `LICENSE` file to the `examples` sub-directory. I think that should cover all concerns

> Btw, do you have a specific package manager in mind?

Someone is currently packaging fire-hpp for the C/C++ package manager Conan:
https://github.com/conan-io/conan-center-index/pull/3405

**Comment by axalon900** [comment]
Yeah, that's me. Hello again.

I'm about ready to just close that PR and just wait for 0.2 (or just forget it entirely) because this has frankly been an infuriating saga. I feel bad enough having pushed this project to accept the structural and CMake changes to help make packaging go nicely, but then on top of that to get a bunch of reviews from people who did nothing but open up this page, look at some dates, and then start countermanding everything with no explanation like this is all one big careless mistake? Yeah, nope.

I'm sorry, I didn't mean for this to be so much trouble.

**Comment by axalon900** [comment]
Sorry, needed to blow off a little steam, which is hard when you also want to remain polite. 😰

I do agree with the suggestion though. If the issue is that the examples are licensed differently, having one license file in the root and another in the examples folder should work.

**Comment by Croydon** [comment]
@axalon900 I'm sorry for your frustration. In the Conan Center Index we have an every increasing amount of activity and pretty much always > 100 open PRs at the same time. The core contributors have by now strong routines and go through a lot of PRs every single day. Through all of these we also have established standards which needs to be meet in order to be able to maintain all of this in the long term. If something seems unclear or illogical, feel free to ask about it in your PR, in new issues or in Slack 😃

**Comment by kongaskristjan** [comment]
Done in d7fe466f9c929b75bfbcb55c55a4f816eed25ad5.

Added Boost and 0BSD licences to / and /examples/ respectively (I erroneously said MIT and 0BSD in a previous comment). I think this was a necessary addition anyway, as some files right now don't have a licence at all.

Can I close the issue?

**Comment by Croydon** [comment]
@kongaskristjan Yes, all done

Thanks 😃

**Comment by axalon900** [comment]
@Croydon It's all good. I really should have just not hit submit and slept on it. I would've deleted the comment but it's probably in everyone's email so I figured I'll "reap what I've sown". ;) I commented in the CCI PR that I'll just close and wait for 0.2 since @kongaskristjan says it should be ready soon, and that would eliminate most points of contention.
